[technote]
id = "RTN-090"
series_id = "RTN"
canonical_url = "https://rtn-090.lsst.io"
github_url = "https://github.com/lsst/rtn-090"
github_default_branch = "main"
date_created = 2024-12-10T02:37:06Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "stable"

[[technote.authors]]
name.given = "Melissa L."
name.family = "Graham"
internal_id = "grahamml"
orcid = "https://orcid.org/0000-0002-9154-3136"
[[technote.authors.affiliations]]
name = "University of Washington"
internal_id = "Washington"
address = "Dept. of Astronomy, Box 351580, Seattle, WA 98195, USA"
[[technote.authors]]
name = {given = "Ryan M.", family = "Lau"}
internal_id = "laur"
orcid = "https://orcid.org/0000-0003-0778-0321"
[[technote.authors.affiliations]]
name = "NSF NOIRLab"
internal_id = "NOIRLab"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
[[technote.authors]]
name = {given = "Leanne P.", family = "Guy"}
internal_id = "guylp"
orcid = "https://orcid.org/0000-0003-0800-8755"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
[[technote.authors]]
name = {given = "Eric C.", family = "Bellm"}
internal_id = "bellme"
orcid = "https://orcid.org/0000-0001-8018-5348"
[[technote.authors.affiliations]]
name = "University of Washington"
internal_id = "Washington"
address = "Dept. of Astronomy, Box 351580, Seattle, WA 98195, USA"
